version: "3"

services:
  api:
    volumes: 
      - .:/go/src/github.com/minhaj10p/facedetect
    container_name: facerec
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080